# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
entryPoints:
  web:
    address: :18080
  traefik:
    address: :8080
providers:
  http:
    endpoint: "http://service:8080/traefik-config"
    pollInterval: "5s"
  file:
    directory: /etc/traefik/config/dynamic
    watch: true
api:
  insecure: true
  dashboard: true
ping: {}
log:
  level: INFO
  format: json
accessLog:
  format: json
